In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

TRAIN_TARGET = "../future-temparture-prediction/Temperature_Train_Target.dat.tsv"

In [2]:
%run ../script/prepocessing.py
Train = TemperatureData('train')
y = np.loadtxt(TRAIN_TARGET)

In [3]:
Train.Temperature.head(2)

year  day  hour    place0    place1    place2    place3    place4  \
0     0    0     0 -0.048063 -0.085799 -0.095233 -0.101522 -0.032340   
1     0    0     2 -0.054352 -0.082654 -0.085799 -0.082654 -0.035485   

     place5    place6    place7    place8    place9   place10  targetplaceid  
0 -0.079510  0.017975  0.014830  0.002251 -0.073220 -0.082654              0  
1 -0.063786  0.021119  0.011685 -0.004038 -0.066931 -0.076365              1

In [4]:
tempers = Train.temperVecPerPlace()

In [5]:
supervisers = [y[Train.TemperPlaceId[i]] for i in xrange(11)]

In [6]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
from sklearn import grid_search
parameters = {'alpha':[float(i)/100 for i in xrange(0,101)]}
clf = [grid_search.GridSearchCV(Ridge(), parameters, cv=10, scoring='mean_squared_error') for i in xrange(11)]

In [22]:
for i in xrange(11):
    print i
    x = tempers[i][:,mask]
    clf[i].fit(x, supervisers[i])
    print clf[i].predict(np.identity(len(mask)))

0
[ 0.33916252  0.28026628 -0.0971565   0.30133549  0.18355247]
1
[ 0.44388629 -0.00636849 -0.06867563  0.28756705  0.34207914]
2
[  6.77637301e-01   3.92867194e-04  -5.31650364e-01   7.30946319e-01
   1.89871714e-01]
3
[ 0.90981253  0.31083143 -0.53965763  0.14285756  0.06838379]
4
[ 0.67099005  0.42780153 -0.08040739  0.11053821 -0.05124318]
5
[ 0.71048065  0.32485156 -0.25494148  0.32261568  0.02910275]
6
[ 0.42631271  0.69357265 -0.29297082  0.44711704 -0.0680643 ]
7
[ 0.21824225  0.28257786  0.33410651  0.21714424  0.05851721]
8
[ 0.35675896  0.18905654 -0.26819105  0.81854003  0.00506602]
9
[ 0.48951819  0.31156586 -0.44687193  0.34187551  0.45131239]
10
[ 0.31849768  0.2928818  -0.47944042  0.10072343  0.74858921]


In [23]:
Test = TemperatureData('test')
tsvec = Test.temperVecPerPlace()

In [9]:
result = np.ndarray(shape=(len(Test.temperVec()),))
for i in xrange(11):
    result[Test.TemperPlaceId[i]] = clf[i].predict(tsvec[i])

In [24]:
for i in xrange(11):
    print i, ":", clf[i].best_score_

0 : -0.00105241965194
1 : -0.00216976217137
2 : -0.00203223908768
3 : -0.00104373869802
4 : -0.00105188182639
5 : -0.000894900978721
6 : -0.00114243325075
7 : -0.000579474384294
8 : -0.00115068542942
9 : -0.00130814439434
10 : -0.00101392801659


In [11]:
s = 0
for i in xrange(11):
    s += -1 * clf[i].best_score_
import math
print math.sqrt(s/11.0)

0.0304528607928


In [5]:
TSP = Train.TSPVecPerPlace()

In [6]:
TSP[0].shape

(164, 33)

In [9]:
supervisers = [y[Train.TemperPlaceId[i]] for i in xrange(11)]

In [10]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
from sklearn import grid_search
parameters = {'alpha':[float(i)/100 for i in xrange(0,101)]}
clf = [grid_search.GridSearchCV(Ridge(), parameters, cv=10, scoring='mean_squared_error') for i in xrange(11)]

In [11]:
for i in xrange(11):
    print i
    clf[i].fit(TSP[i], supervisers[i])
    print clf[i].predict(np.identity(33))

0
[ 0.54392486  0.07958291  0.21778347  0.30753395  0.02009961 -0.12784141
  0.2138663  -0.18895367  0.10323691 -0.00072331 -0.03326375 -0.01871107
  0.07743051  0.02748946 -0.00610162  0.00521353  0.02599331  0.02156556
  0.03410737  0.03468113 -0.02080148  0.05174167 -0.05706094  0.07654863
 -0.03180542 -0.10675492 -0.02055972  0.05216364  0.04527378 -0.05058708
 -0.03025986 -0.06508807  0.18986454]
1
[-0.12445626  0.75701154  0.22986587  0.31751311 -0.07757862 -0.03563679
  0.12357556 -0.13046524  0.04111723 -0.03439344  0.07284753 -0.03708903
  0.03780882  0.02090154  0.05644298  0.02290795 -0.00835598  0.04959965
 -0.04579725  0.11659623 -0.00197001  0.02953146  0.07933869  0.0025022
 -0.01513115  0.07158678 -0.00093392  0.0256984  -0.04297887 -0.0848901
 -0.08921364 -0.02037355  0.10912271]
2
[-0.02117674  0.12768783  0.69183832  0.419501   -0.09102731 -0.02553318
  0.11559948 -0.19135006  0.06956823 -0.01213402  0.02825165 -0.02461299
  0.05106626 -0.01256013  0.05255092  0.0438

In [12]:
Test = TemperatureData('test')
tspvec = Test.TSPVecPerPlace()

In [15]:
result = np.ndarray(shape=(len(Test.temperVec()),))
for i in xrange(11):
    result[Test.TemperPlaceId[i]] = clf[i].predict(tspvec[i])

In [16]:
result.shape

(1800,)

In [17]:
np.savetxt("../result/sub.dat", result, fmt='%.10f')

In [18]:
for i in xrange(11):
    print i, ":", clf[i].best_score_

0 : -0.000665426949251
1 : -0.000950182472833
2 : -0.000981704290296
3 : -0.00107756073007
4 : -0.000594147946519
5 : -0.00100879799012
6 : -0.00112037063434
7 : -0.000669610258042
8 : -0.000847290502859
9 : -0.000934889711468
10 : -0.00110910751202


In [19]:
s = 0
for i in xrange(11):
    s += -1 * clf[i].best_score_
import math
print math.sqrt(s/11.0)

0.0300893955917


In [ ]:
- 0.000680181523483 - 0.000891537297341 - 0.00124278373553 - 0.00107737795569 - 0.000638463439515 - 0.000873899810087 - 0.00102558901443 - 0.000603305923792 - 0.00104195722415 - 0.00114390321264 - 0.000982144898467

In [6]:
k = 0.000665426949251 + 0.000950182472833+0.000981704290296+0.00107756073007+0.000594147946519+0.00100879799012+0.00112037063434+0.000669610258042+0.000847290502859+0.000934889711468+0.00110910751202

In [9]:
import math
math.sqrt(k/11.0)

0.03008939559170911